################################################################################
#
# wpa_supplicant_s1g
#
################################################################################
#WPA_SUPPLICANT_S1G_VERSION = $(call qstrip,$(BR2_PACKAGE_WPA_SUPPLICANT_S1G_VERSION))
#WPA_SUPPLICANT_S1G_SITE = $(call qstrip,$(BR2_PACKAGE_WPA_SUPPLICANT_S1G_SITE))
WPA_SUPPLICANT_S1G_VERSION = rel_1_11_3_2024_Mar_28
WPA_SUPPLICANT_S1G_SITE = /dl
#WPA_SUPPLICANT_S1G_SITE_METHOD = git
WPA_SUPPLICANT_S1G_LICENSE = BSD-3-Clause
WPA_SUPPLICANT_S1G_LICENSE_FILES = README
WPA_SUPPLICANT_S1G_GIT_DESCRIBE_DIR = $(if $(WPA_SUPPLICANT_S1G_OVERRIDE_SRCDIR),$(WPA_SUPPLICANT_S1G_OVERRIDE_SRCDIR),$(WPA_SUPPLICANT_S1G_DL_DIR)/git)
WPA_SUPPLICANT_S1G_GIT_DESCRIBE = $(shell git -C $(WPA_SUPPLICANT_S1G_GIT_DESCRIBE_DIR) describe --always --dirty)
WPA_SUPPLICANT_S1G_CONFIG = $(WPA_SUPPLICANT_S1G_DIR)/wpa_supplicant/.config
WPA_SUPPLICANT_S1G_SUBDIR = wpa_supplicant
WPA_SUPPLICANT_S1G_DBUS_OLD_SERVICE = fi.epitest.hostap.WPASupplicant
WPA_SUPPLICANT_S1G_DBUS_NEW_SERVICE = fi.w1.wpa_supplicant1
WPA_SUPPLICANT_S1G_CFLAGS = $(TARGET_CFLAGS) -I$(STAGING_DIR)/usr/include/libnl3/ -I$(STAGING_DIR)/usr/include/libopenssl/
#WPA_SUPPLICANT_S1G_CFLAGS = $(TARGET_CFLAGS)
WPA_SUPPLICANT_S1G_LDFLAGS = $(TARGET_LDFLAGS)

# install the wpa_client library
WPA_SUPPLICANT_S1G_INSTALL_STAGING = YES

WPA_SUPPLICANT_S1G_CONFIG_EDITS =

# Add support for simple background scan
WPA_SUPPLICANT_S1G_CONFIG_SET = CONFIG_UBUS

WPA_SUPPLICANT_S1G_CONFIG_ENABLE = \
	CONFIG_IEEE80211AC \
	CONFIG_IEEE80211N \
	CONFIG_IEEE80211AH \
	CONFIG_IEEE80211R \
	CONFIG_INTERNAL_LIBTOMMATH \
	CONFIG_DEBUG_FILE \
	CONFIG_MATCH_IFACE \
	CONFIG_SAE \
	CONFIG_TESTING_OPTIONS \
	CONFIG_PMKSA_CACHE_EXTERNAL \
	CONFIG_WNM \
	CONFIG_S1G_TWT \
	CONFIG_MORSE_STANDBY_MODE \
	CONFIG_MORSE_KEEP_ALIVE_OFFLOAD \
	CONFIG_IEEE80211W 

WPA_SUPPLICANT_S1G_CONFIG_DISABLE = \
	CONFIG_SMARTCARD \
	CONFIG_BGSCAN_SIMPLE \
	CONFIG_SMARTCARD \
	CONFIG_CTRL_IFACE_DBUS_NEW \
	CONFIG_CTRL_IFACE_DBUS_INTRO \
	CONFIG_READLINE \
	CONFIG_DPP \
	CONFIG_DPP2 \
	CONFIG_DPP3


# libnl-3 needs -lm (for rint) and -lpthread if linking statically
# And library order matters hence stick -lnl-3 first since it's appended
# in the wpa_supplicant Makefiles as in LIBS+=-lnl-3 ... thus failing
ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_NL80211),y)
ifeq ($(BR2_STATIC_LIBS),y)
WPA_SUPPLICANT_S1G_LIBS += -lnl-3 -lm -lpthread
endif
#WPA_SUPPLICANT_S1G_LIBS += -L$(STAGING_DIR)/usr/static/libnl -lnl-3 -lm -lpthread -static
WPA_SUPPLICANT_S1G_DEPENDENCIES += host-pkgconf libnl
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_LIBNL32
else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += CONFIG_DRIVER_NL80211
endif

# Trailing underscore on purpose to not enable CONFIG_EAPOL_TEST
ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_EAP),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_EAP_
# uses dlopen()
ifeq ($(BR2_STATIC_LIBS),y)
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += CONFIG_EAP_TNC
endif
else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += CONFIG_EAP
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_HOTSPOT),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_HS20 \
	CONFIG_INTERWORKING
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_AP_SUPPORT),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += \
	CONFIG_AP \
	CONFIG_P2P
else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += \
	CONFIG_AP \
	CONFIG_P2P
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_WIFI_DISPLAY),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_WIFI_DISPLAY
else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += CONFIG_WIFI_DISPLAY
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_MESH_NETWORKING),y)
WPA_SUPPLICANT_S1G_CONFIG_SET += CONFIG_MESH
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_IEEE80211W
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_AUTOSCAN),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += \
	CONFIG_AUTOSCAN_EXPONENTIAL \
	CONFIG_AUTOSCAN_PERIODIC
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_WPS),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_WPS
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_WPA3),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += \
	CONFIG_DPP \
	CONFIG_SAE \
	CONFIG_OWE
else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += \
	CONFIG_DPP \
	CONFIG_SAE \
	CONFIG_OWE
endif

# Try to use openssl if it's already available
ifeq ($(BR2_PACKAGE_LIBOPENSSL),y) 
WPA_SUPPLICANT_S1G_DEPENDENCIES += host-pkgconf libopenssl
#WPA_SUPPLICANT_S1G_LIBS += `$(PKG_CONFIG_HOST_BINARY) --libs openssl`
#WPA_SUPPLICANT_S1G_LIBS += -L$(STAGING_DIR)/usr/static/libopenssl/ -lssl -lcrypto -lz -lpthread -ldl
WPA_SUPPLICANT_S1G_LIBS += -L$(STAGING_DIR)/usr/static/libopenssl/ -lcrypto -lz -lpthread -ldl

WPA_SUPPLICANT_S1G_CONFIG_EDITS += 's/\#\(CONFIG_TLS=openssl\)/\1/'
else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += CONFIG_EAP_PWD
WPA_SUPPLICANT_S1G_CONFIG_EDITS += 's/\#\(CONFIG_TLS=\).*/\1internal/'
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_DBUS),y)
WPA_SUPPLICANT_S1G_DEPENDENCIES += host-pkgconf dbus
WPA_SUPPLICANT_S1G_MAKE_ENV = \
	PKG_CONFIG_SYSROOT_DIR="$(STAGING_DIR)" \
	PKG_CONFIG_PATH="$(STAGING_DIR)/usr/lib/pkgconfig"
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_CTRL_IFACE_DBUS_NEW
define WPA_SUPPLICANT_S1G_INSTALL_DBUS_NEW
	$(INSTALL) -m 0644 -D \
		$(@D)/wpa_supplicant/dbus/$(WPA_SUPPLICANT_S1G_DBUS_NEW_SERVICE).service \
		$(TARGET_DIR)/usr/share/dbus-1/system-services/$(WPA_SUPPLICANT_S1G_DBUS_NEW_SERVICE).service
endef

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_DBUS_INTROSPECTION),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_CTRL_IFACE_DBUS_INTRO
endif

else
WPA_SUPPLICANT_S1G_CONFIG_DISABLE += CONFIG_CTRL_IFACE_DBUS_NEW
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_DEBUG_SYSLOG),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_DEBUG_SYSLOG
endif

ifeq ($(BR2_PACKAGE_READLINE),y)
WPA_SUPPLICANT_S1G_DEPENDENCIES += readline
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_READLINE
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_WPA_CLIENT_SO),y)
WPA_SUPPLICANT_S1G_CONFIG_SET += CONFIG_BUILD_WPA_CLIENT_SO
define WPA_SUPPLICANT_S1G_INSTALL_WPA_CLIENT_SO
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/libwpa_client.so \
		$(TARGET_DIR)/usr/lib/libwpa_client.so
	$(INSTALL) -m 0644 -D $(@D)/src/common/wpa_ctrl.h \
		$(TARGET_DIR)/usr/include/wpa_ctrl.h
endef
define WPA_SUPPLICANT_S1G_INSTALL_STAGING_WPA_CLIENT_SO
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/libwpa_client.so \
		$(STAGING_DIR)/usr/lib/libwpa_client.so
	$(INSTALL) -m 0644 -D $(@D)/src/common/wpa_ctrl.h \
		$(STAGING_DIR)/usr/include/wpa_ctrl.h
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_DPP),y)
WPA_SUPPLICANT_S1G_CONFIG_SET += \
	CONFIG_DPP \
	CONFIG_DPP2 \
	CONFIG_DPP3 \
	CONFIG_INTERWORKING
endif

ifeq ($(BR2_PACKAGE_SUNMI_ADD),y)
WPA_SUPPLICANT_S1G_CONFIG_ENABLE += CONFIG_SUNMI_ADD_S1G_ASSOCLIST
WPA_SUPPLICANT_S1G_CONFIG_SET += CONFIG_SUNMI_ADD_S1G_ASSOCLIST
endif

define WPA_SUPPLICANT_S1G_CONFIGURE_CMDS
	cp $(@D)/wpa_supplicant/defconfig $(WPA_SUPPLICANT_S1G_CONFIG)
	sed -i $(patsubst %,-e 's/^#\(%\)/\1/',$(WPA_SUPPLICANT_S1G_CONFIG_ENABLE)) \
		$(patsubst %,-e 's/^\(%\)/#\1/',$(WPA_SUPPLICANT_S1G_CONFIG_DISABLE)) \
		$(patsubst %,-e '1i%=y',$(WPA_SUPPLICANT_S1G_CONFIG_SET)) \
		$(patsubst %,-e %,$(WPA_SUPPLICANT_S1G_CONFIG_EDITS)) \
		$(WPA_SUPPLICANT_S1G_CONFIG)
endef

# LIBS for wpa_supplicant, LIBS_c for wpa_cli, LIBS_p for wpa_passphrase
define WPA_SUPPLICANT_S1G_BUILD_CMDS
	$(TARGET_MAKE_ENV) CFLAGS="$(WPA_SUPPLICANT_S1G_CFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS)" BINDIR=/usr/sbin \
		LIBS="$(WPA_SUPPLICANT_S1G_LIBS)" LIBS_c="$(WPA_SUPPLICANT_S1G_LIBS)" \
		LIBS_p="$(WPA_SUPPLICANT_S1G_LIBS)" \
		$(MAKE) MORSE_VERSION="$(WPA_SUPPLICANT_S1G_GIT_DESCRIBE)" CC="$(TARGET_CC)" -C $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)
endef

ifeq ($(BR2_S1G_UPSTREAM),y)
ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_CLI),y)
define WPA_SUPPLICANT_S1G_INSTALL_CLI
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/wpa_cli \
		$(TARGET_DIR)/usr/sbin/wpa_cli_s1g
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_PASSPHRASE),y)
define WPA_SUPPLICANT_S1G_INSTALL_PASSPHRASE
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/wpa_passphrase \
		$(TARGET_DIR)/usr/sbin/wpa_passphrase_s1g
endef
endif

ifeq ($(BR2_PACKAGE_DBUS),y)
define WPA_SUPPLICANT_S1G_INSTALL_DBUS
	$(INSTALL) -m 0644 -D \
		$(@D)/wpa_supplicant/dbus/dbus-wpa_supplicant.conf \
		$(TARGET_DIR)/etc/dbus-1/system.d/wpa_supplicant_s1g.conf
	$(WPA_SUPPLICANT_S1G_INSTALL_DBUS_OLD)
	$(WPA_SUPPLICANT_S1G_INSTALL_DBUS_NEW)
endef
endif

define WPA_SUPPLICANT_S1G_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/wpa_supplicant \
		$(TARGET_DIR)/usr/sbin/wpa_supplicant_s1g
	$(INSTALL) -m 644 -D $(WPA_SUPPLICANT_S1G_PKGDIR)/wpa_supplicant_s1g.conf \
		$(TARGET_DIR)/etc/wpa_supplicant_s1g.conf
	$(WPA_SUPPLICANT_S1G_INSTALL_CLI)
	$(WPA_SUPPLICANT_S1G_INSTALL_PASSPHRASE)
	$(WPA_SUPPLICANT_S1G_INSTALL_DBUS)
	$(WPA_SUPPLICANT_S1G_INSTALL_WPA_CLIENT_SO)
endef
else

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_CLI),y)
define WPA_SUPPLICANT_S1G_INSTALL_CLI
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/wpa_cli_s1g \
		$(TARGET_DIR)/usr/sbin/wpa_cli_s1g
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_S1G_PASSPHRASE),y)
define WPA_SUPPLICANT_S1G_INSTALL_PASSPHRASE
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/wpa_passphrase_s1g \
		$(TARGET_DIR)/usr/sbin/wpa_passphrase_s1g
endef
endif

ifeq ($(BR2_PACKAGE_DBUS),y)
define WPA_SUPPLICANT_S1G_INSTALL_DBUS
	$(INSTALL) -m 0644 -D \
		$(@D)/wpa_supplicant/dbus/dbus-wpa_supplicant_s1g.conf \
		$(TARGET_DIR)/etc/dbus-1/system.d/wpa_supplicant_s1g.conf
	$(WPA_SUPPLICANT_S1G_INSTALL_DBUS_OLD)
	$(WPA_SUPPLICANT_S1G_INSTALL_DBUS_NEW)
endef
endif


define WPA_SUPPLICANT_S1G_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/wpa_supplicant_s1g \
		$(TARGET_DIR)/usr/sbin/wpa_supplicant_s1g
	#$(INSTALL) -m 644 -D $(WPA_SUPPLICANT_S1G_PKGDIR)/wpa_supplicant_s1g.conf \
	$(INSTALL) -m 644 -D $(WPA_SUPPLICANT_S1G_PKGDIR)/package/wpa_supplicant_s1g/wpa_supplicant_s1g.conf \
		$(TARGET_DIR)/etc/wpa_supplicant_s1g.conf
	$(WPA_SUPPLICANT_S1G_INSTALL_CLI)
	$(WPA_SUPPLICANT_S1G_INSTALL_PASSPHRASE)
	$(WPA_SUPPLICANT_S1G_INSTALL_DBUS)
	$(WPA_SUPPLICANT_S1G_INSTALL_WPA_CLIENT_SO)
endef
endif

define WPA_SUPPLICANT_S1G_INSTALL_STAGING_CMDS
	$(WPA_SUPPLICANT_S1G_INSTALL_STAGING_WPA_CLIENT_SO)
endef

define WPA_SUPPLICANT_S1G_INSTALL_INIT_SYSTEMD
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/systemd/wpa_supplicant.service \
		$(TARGET_DIR)/usr/lib/systemd/system/wpa_supplicant.service
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/systemd/wpa_supplicant@.service \
		$(TARGET_DIR)/usr/lib/systemd/system/wpa_supplicant@.service
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/systemd/wpa_supplicant-nl80211@.service \
		$(TARGET_DIR)/usr/lib/systemd/system/wpa_supplicant-nl80211@.service
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_S1G_SUBDIR)/systemd/wpa_supplicant-wired@.service \
		$(TARGET_DIR)/usr/lib/systemd/system/wpa_supplicant-wired@.service
endef

$(eval $(generic-package))
